migrate=api:makemigrations module_template && api:migrate
patterns-check=win:virtual_env\python\Scripts\python.exe modules\module_template\scripts\patterns_check.py && linux:virtual_env/python/bin/python modules/module_template/scripts/patterns_check.py
